---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:545009829015:task-definition/forbluegreen:1"
        LoadBalancerInfo:
          ContainerName: "flaskcont"
          ContainerPort: 8080
