---
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:545009829015:task-definition/blue-green-task:1"
        LoadBalancerInfo:
          ContainerName: "bluegreencontainer"
          ContainerPort: 80
