version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing jq...
      - yum install -y jq
      - echo Installing Maven...
      - yum install -y maven
      - echo Building the JAR file...
      - mvn clean install
      - echo Logging in to Docker Hub...
      - DOCKER_USERNAME=$(aws secretsmanager get-secret-value --secret-id dockerhub/credentials --query SecretString --output text | jq -r .username)
      - DOCKER_PASSWORD=$(aws secretsmanager get-secret-value --secret-id dockerhub/credentials --query SecretString --output text | jq -r .password)
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t project6image .
      - docker tag project6image:latest jatha1994/project6image:latest

  post_build:
    commands:
      - echo Pushing Docker image to Docker Hub...
      - docker push jatha1994/project6image:latest
      - echo Writing imagedefinitions.json...
      - ls -l
      - printf '[{"name":"sprinrajco","imageUri":"jatha1994/project6image:latest"}]' > imagedefinitions.json
      - echo Writing appspec.yml...
      

artifacts:
  files:
    - imagedefinitions.json
    - appspec.yml
    - target/demo-1.0.0.jar
